import { VerticalBox } from "std-widgets.slint";
import { PasswordInputComponent } from "passwordinput.slint";
export component ZxcvbnUI inherits Window {
    VerticalBox {
        padding: 50px;
        alignment: center;
        Text {
            text: "Zxcvbn Entropy Calculator";
            horizontal-alignment: center;
            font-size: 32px;
        }
        PasswordInputComponent {
            
        }
    }
}