import { LineEdit, Button , VerticalBox} from "std-widgets.slint";

export component PasswordInputComponent {
    property<string> password: "";

    VerticalBox {
        alignment: center;
        LineEdit {
            height: 24px;
            placeholder_text: "Enter password";
            input-type: InputType.password; // Hides the password input
            accepted => {
                root.password = self.text;
            }
        }
    
        Button {
            text: "Submit";
        }
    }
}